overlays:

### SHOW STATUS ###

  Weekly:
    overlay:
      file: config/overlays/status-top-left/airing.png
      name: airing
      group: STATUS
      weight: 900
    tmdb_on_the_air: 5000

  Returning:
    overlay:
      file: config/overlays/status-top-left/returning.png
      name: returning
      group: STATUS
      weight: 800
    plex_all: true
    filters:
      tmdb_status:
         - returning
         - planned
         - production

  Ended:
    overlay:
      file: config/overlays/status-top-left/ended.png
      name: ended
      group: STATUS
      weight: 600
    plex_all: true
    filters:
      tmdb_status:
         - ended

  Cancelled:
    overlay:
      name: cancelled
      file: config/overlays/status-top-left/cancelled.png
      group: STATUS
      weight: 700
    plex_all: true
    filters:
      tmdb_status:
         - canceled

### SHOW STATUS ###